# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
campgrounds = [
    {name: "Buckhorn Campground", description:"The elevation is 6,500 ft. This campground with a wonderful blend of different trees, mainly large Jeffrey pine and cedar, is located in a cool and shady dale or gentle canyon carved by a creek that meanders throughout the area. The patches of fern and wildflowers, e.g., Shooting Star, add to the character of this gorgeous campground, which is particularly well suited for tent campers. A community fire pit is available for groups to enjoy a few campfire stories. This is a campground where the whole family can enjoy a real forest. Although there are no grilles, each campsite has a fire ring. This is bear country; practice safe food storage techniques.", location_id: 1, cost: 12, link:"https://www.fs.usda.gov/recarea/angeles/recarea/?recid=41690"},
    {name: "Chilao", description: "Chilao Campground offers two different loops for tent camping, Little Pines, and Manzanita. Each loop offers 40+ sites for camping. Driving to the campground only takes an hour and a half away from downtown Los Angeles weaving up Angeles Crest Highway (HWY 2). The campground sits at an elevation of 5,300 feet, giving campers majestic panoramas of nearby Vetter Lookout and Big Tujunga Canyon. Both loops remain open until a major snowfall makes it impossible to enter a loop. It's also important to note that wildlife is very active in this area and campers should ensure they secure their food in proper receptacles.", location_id:1, cost: 12, link:"https://www.fs.usda.gov/recarea/angeles/recreation/camping-cabins/recarea/?recid=41780&actid=29"},
    {name: "Guffy Campground", description:"8,300-foot elevation. 8 trailside campsites overlooking the Sheep Mountain Wilderness Area. Primitive tent camping site overlooking the Sheep Mountain Wilderness Area. No water. Vault toilets. Adventure Pass/Interagency Pass required for vehicles parked at this campground. Campsites are first come - first served. Groceries and services are available in the community of Wrightwood (approximately 9.5 miles).", location_id:1, cost:0, link:"hhttps://www.fs.usda.gov/recarea/angeles/recarea/?recid=41730"},
    {name: "Manker Campground", description:"Camp high in the clouds at Manker Flats Campground. This campground sits at 6000-feet and offers 21 campsites open year-round. However, piped-water is turned once temperatures reach freezing.  Each site comes with a spacious spot for all your family camping needs and includes a picnic bench, fire ring, and vault toilets. It's located within a short drive to historic Mt. Baldy Schoolhouse and Visitor Center where visitors can discover the land's Native American roots.", location_id:1, cost: 12, link:"https://www.fs.usda.gov/recarea/angeles/recarea/?recid=41776"},
    {name: "Coldbrook Campground", description:"Coldbrook Campground offers 22 shaded campsites* at the intersection of Coldbrook and Soldier Creeks that are open year round. Available on a first-come, first-serve basis, each campsite can fit up eight people and two vehicles (additional fee applies for the second vehicle). This campground is less populated then nearby Crystal Lake Recreation Area. However, it does reach capacity on most summer weekends. Each campsite has a fire pit and grill, and picnic tables are available on the grounds. Potable water is available on the campgrounds. ", location_id:1, cost: 12, link:"https://www.fs.usda.gov/recarea/angeles/recarea/?recid=41772"},
    {name: "Crystal Lake", description:"Crystal Lake Recreation Area Campground, located at the top of HWY 39 (mile marker 38.13) offers four loops of camping for a total of 50 campsites. Each campsite is $12/night and is first-come-first-served year-round. Outdoor adventures lie around every corner - including hikes to spectacular peaks of Mt. Islip and Windy Gap or fishing in Crystal Lake. ", location_id:1, cost:12, link:"hhttps://www.fs.usda.gov/recarea/angeles/recreation/recarea/?recid=41686&actid=43"},
    {name: "Lodgepole Campground", description:"Lodgepole Campground is two miles (3 km) from the Giant Forest sequoia grove and 21 miles (34 km) from the Sequoia National Park entrance. This large, popular campground is ¼-mile from Lodgepole Village along the Marble Fork of the Kaweah River. Lodgepole Campground is in a lodgepole pine forest at an elevation of 6,700 ft (2,042 m). In summer, the free Sequoia Shuttle to Giant Forest stops within the campground.", location_id:2, cost: 22, link:"https://www.nps.gov/seki/planyourvisit/lodgepole.htm"},
    {name: "Dorst Campground", description:"Dorst Creek Campground, located between Grant Grove and Giant Forest, offers a central location from which to explore the parks. This campground is 10 miles (16 km) from the Giant Forest, under open stands of evergreen trees at an elevation of 6,800 feet (2,073 m). The free Sequoia Shuttle stops at the campground.", location_id:2, cost: 22, link:"https://www.nps.gov/seki/planyourvisit/dorst.htm"},
    {name: "Sentinel Campground", description:"Sentinel Campground in Cedar Grove is nestled in the stunning Kings Canyon, one of the deepest canyons in the United States. With views of a lovely meadow central to the campground, the sound of the Kings River, and glowing mountainsides just beyond the trees, Sentinel Campground is a wonderful place for families to spend time in the great outdoors.", location_id:2, cost: 22, link:"https://www.recreation.gov/camping/campgrounds/253917"},
    {name: "Big Meadows Campground", description:"Big Meadows Campground is located 75 miles east of Fresno, California, in the Sequoia National Forest and Sequoia National Monument. The campground sits at an elevation of 7,500 feet and has views of the meadow and surrounding mountains. ", location_id:2, cost: 25, link:"https://www.recreation.gov/camping/campgrounds/256932"},
    {name: "Potwisha Campground", description:"Potwisha Campground, located along the Generals Highway in Sequoia National Park, offers convenience for visiting the many attractions in the park. The campground is situated along the Marble Fork of the Kaweah River, just four miles from the park entrance, in the Sierra Foothills.", location_id:2, cost: 22,link:"https://www.recreation.gov/camping/campgrounds/249979"},
    {name: "Princess", description:"Princess Campground sits next to a large meadow at an elevation of 5,900 feet in the Indian Basin Grove. The campsite is just 3 miles northwest of Hume Lake. The 87-acre lake was built to support a one-time commercial logging operation, and is part of the Kings River Watershed, a region of the Sierra Nevada mountains replete with vast stands of timber. The lake now provides countless recreational opportunities for visitors.", location_id:2, cost:29, link:"https://www.recreation.gov/camping/campgrounds/232782"},
    {name: "Pine Mountain Campground", description:"Perfectly situated high above the Sespe Wilderness offering stunning views of the valley below and the Channel Islands in the distance lies Pine Mountain Campground. You will find yourself surrounded by moderate hills, tall pine trees and the sounds of silence. At an elevation of 6,650 feet, it offers cooler temperatures on hot summer days, and a chance to let everything else go as you take in all that nature has to offer.", location_id:3, cost: 20, link:"https://www.recreation.gov/camping/campgrounds/273843"},
    {name: "Reyes Creek Campground", description:"Hammock spots, dipping holes and a fishing stream make Reyes Creek Campground an ideal hideaway. Located near the Sespe Wilderness alongside Reyes Creek you will find renewal and replenishment, Reyes Creek-style.", location_id:3, cost: 20, link:"https://modernhiker.com/hike/hiking-los-liones-trail-to-parker-mesa/https://www.recreation.gov/camping/campgrounds/273877"},
    {name: "Campo Alto", description:"Tucked away high atop the Cerro Noroeste, you'll find solitude, serenity and unsurpassed scenery as you lose yourself in a pleasant grove of Jeffrey pines at Campo Alto Campground. Campsites are spacious, the air is filled with a pine-sweet scent, and you will enjoy end-of-the-road privacy. Invigorated by the fresh air, your inner hiker will hunger to head out on the Vincent Tumameit Trailhead to enjoy the scenic mountain vistas. Do your best to leave this natural setting just as you found it. The campsites have no barriers to block your view, so most modest sized RVs, and all tent campers fit well here.", location_id:3, cost: 20, link:"https://www.recreation.gov/camping/campgrounds/273842"},
    {name: "McGill Campground", description:"Escape from the city to the remote and beautiful McGill Campground. The campground, bursting with views of mountains and valleys, is an ideal base for several biking and hiking trails. A dense stand of Jeffrey pine and ponderosa pine shade the campground and each campsite is nicely spaced.", location_id:3, cost:20, link:"https://www.recreation.gov/camping/campgrounds/231962"},
    {name: "Four Jeffrey", description:"Four Jeffrey is a mostly shaded campground with gorgeous views of Table Mountain along the South Fork of Bishop Creek. Campers enjoy fishing and swimming in the trout-stocked creek. The nearby John Muir Wilderness provides plenty of hiking opportunities to view impressive lakes and glaciers.", location_id:4, cost: 28, link:"https://www.recreation.gov/camping/campgrounds/233807"},
    {name: "Big Pine Creek Campground", description:"Big Pine Creek Campground, surrounded by sprawling meadows and towering trees, is perfectly situated in the scenic Big Pine Canyon. Campsites are perched along the cool, fish-filled waters of Big Pine Creek. Big Pine Canyon is heralded for having both the largest and southern most glaciers in the Sierra Nevada mountains. The campground sits at 7,700 feet elevation among vegetation like Jeffrey pine, sagebrush, aspen and cottonwood trees.", location_id:4, cost:21, link:"https://www.recreation.gov/camping/campgrounds/232305"},
    {name: "Upper Sage Flat", description:"Take the family to Upper Sage for a pleasant camping trip along the banks of Big Pine Creek. Here, visitors can experience the beauty of the creek that runs along the base of a narrow canyon. Visitors can swim or fish, in the creek that is stocked annually with trout, or head to a nearby lake for power boating.", location_id:4, cost:25, link:"https://www.recreation.gov/camping/campgrounds/232242"},
    {name: "East Fork California", description:"East Fork Canyon is in a beautiful wooded section of Rock Creek Canyon, near Lower Rock Creek. Anglers, hikers and photographers enjoy this scenic location in the eastern Sierra Nevada Mountains of California. The facility is large and accommodating, with several loops of campsites.Opening and closing dates for the season are dependent on weather.", location_id:4, cost:27, link:"https://www.recreation.gov/camping/campgrounds/232396"},
    {name: "French Camp", description:"French Camp lies in the Rock Creek area of the scenic Sierra Nevada Mountains, near Tom's Place and midway between Bishop and Mammoth Lakes, California. Its ideal location makes this campground a good stop for travelers on U.S. Highway 395 to rest overnight. Hiking opportunities are vast, and the creekside campground is convenient for fishing. The facility is large and inviting, with forest and mountain views and several amenities. Opening and closing dates for the season are dependent on weather.", location_id:4, cost:27, link:"https://www.recreation.gov/camping/campgrounds/232395"},
    {name: "North Pines", description:"North Pines Campground is located in breathtaking Yosemite National Park in Central California's rugged Sierra Nevada Mountain Range at an elevation of 4000 feet. The site is situated in the heart of Yosemite Valley, an awe-inspiring landscape containing many of the famous features for which Yosemite National Park is known. Within Yosemite, visitors can gaze upon waterfalls, sheer granite cliffs, deep valleys, grand meadows, ancient giant sequoias, vast wilderness areas and so much more. Yosemite National Park's reservable campsites are available up to five months in advance on the 15th of each month at 7:00 a.m. (PT) or 10:00 a.m. (ET). For example, on January 15, the time period May 15 to June 14 becomes available to reserve, and therefore, the full booking window would be from January 16 to June 14.", location_id:5, cost:26, link:"https://www.recreation.gov/camping/campgrounds/232449"},
    {name: "Tuolumne Meadows", description:"Tuolumne Meadows Campground is located in breathtaking Yosemite National Park in Central California's rugged Sierra Nevada Mountain Range at an elevation of 8,600 feet. The site is situated along the scenic Tioga Road just five miles from the Tioga Pass Entrance Station. Within Yosemite, visitors can gaze upon waterfalls, sheer granite cliffs, deep valleys, grand meadows, ancient giant sequoias, vast wilderness areas, and so much more. Yosemite National Park's reservable campsites are available up to five months in advance on the 15th of each month at 7:00 a.m. (PT) or 10:00 a.m. (ET). For example, on January 15, the time period May 15 to June 14 becomes available to reserve, and therefore, the full booking window would be from January 16 to June 14.", location_id:5, cost:26, link:"https://www.recreation.gov/camping/campgrounds/232448"},
    {name: "Wawona", description:"Wawona Campground is located in breathtaking Yosemite National Park in Central California's rugged Sierra Nevada Mountain Range. The site is situated at the southern end of the park, 27 miles and 45 minutes from Yosemite Valley, at an elevation of 4000 feet. Wawona was home to the park's headquarters in 1904 and historic structures still stand today. The majestic Mariposa Grove of Giant Sequoias is just a short drive away. Within Yosemite, visitors gaze upon waterfalls, sheer granite cliffs, deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area and much more. Yosemite National Park's reservable campsites are available up to five months in advance on the 15th of each month at 7:00 a.m. (PT) or 10:00 a.m (ET). For example, on January 15, the time period May 15 to June 14 becomes available to reserve, and therefore, the full booking window would be from January 16 to June 14.", location_id:5, cost: 26, link: "https://www.recreation.gov/camping/campgrounds/232446"},
    {name: "Circle X Ranch", description:"Tucked in the canyons above Malibu and nestled below majestic Boney Mountain, you will find Circle X Ranch. This former Boy Scout camp offers many opportunities for exploration and adventure. Journey to Sandstone Peak, the highest point in the Santa Monica Mountains, and see several of the Channel Islands on a clear day. Enjoy a visit to the Grotto or a creekside picnic. Reserve the Group Camp and listen to coyote songs at night.", location_id:6, cost: 35, link:"https://www.recreation.gov/camping/campgrounds/233381"},
    {name: "Malibu Creek State Park Campground", description:"Malibu Creek State Park Campground is located up Malibu Canyon, 6½ miles north of Highway 1 near Malibu Lagoon and 3½ miles south of Highway 101. The park offers a scenic mountain destination within easy driving distance of the Los Angeles area. Visitors enjoy wildlife, hiking, bird watching, and summer campfire programs.", location_id:7, cost:45, link:"http://www.californiasbestcamping.com/angeles/malibu_creek.html"},
    {name: "Stone Creek", description:"The bigger of the two drive-in campgrounds, Stone Creek hosts 50 sites, (7 of which include water faucets). You won’t find showers, but you will find plenty of access to nature trails where you can toss aside your concerns about ‘clean’ and ‘dirty’ and relish the blurred lines of wilderness living. Pay and extra fee and bring your dog along to Stone Creek to partake in the camping experience!", location_id:8, cost:25, link:"https://www.hipcamp.com/california/mount-san-jacinto/stone-creek-campground"},
    {name: "Idyllwild Campground", description:"Idyllwild Campground has 31 developed campsites. Nine sites are designated for tents only. All the rest of the campsites can accommodate RVs, trailers, and tents. A couple of those campsites have full hook-ups, while campsites 4, 5, 6, and 28 have electric hook-ups. There is also a Hike & Bike site available for those arriving on foot or by bicycle.", location_id:8, cost: 25, link:"http://www.californiasbestcamping.com/san_jacinto/idyllwild.html"},
    {name: "Dogwood", description:"Dogwood Campground is a family-friendly facility located in the heart of the San Bernardino National Forest. All sites must be reserved to enjoy the area's scenic surroundings and plentiful recreational opportunities.", location_id:9, cost:37, link:"https://www.recreation.gov/camping/campgrounds/232037"},
    {name: "Hanna Flat", description:"Hanna Flat Campground is a family-friendly facility nestled in the pine-covered mountains of Southern California. It offers access to a variety of outdoor recreational opportunities and a beautiful location to enjoy nature.", location_id:9, cost: 30,link:"https://www.recreation.gov/camping/campgrounds/232249"},
    {name: "Barton Flats", description:"The Barton Flats Campground provides a taste of just about everything the San Bernardino National Forest has to offer. In addition to a nearby lake and river access, a variety hiking, biking and horseback riding trails can be accessed from the campground. Its location also provides a great place for visitors to relax, take in the fresh, mountain air, and enjoy the beautiful scenery.", location_id:9, cost:33, link:"https://www.recreation.gov/camping/campgrounds/231975"},
    {name: "San Gorgonio", description:"The San Gorgonio Campground provides access to a variety of recreational opportunities, as well as a beautiful location in which to enjoy nature. Its proximity to scenic trails and nearby mountain lakes and streams make the campground a great place to bring the family to relax and get away from it all.", location_id:9, cost:31, link:"https://www.recreation.gov/camping/campgrounds/231976"},
    {name: "Santa Rosa Island", description:"The island has rich archeological resources as well. It is home to thousands of significant archeological sites of the Chumash Native Americans, who inhabited the island until 1820. Others have come to the island during more recent centuries to exploit its rich resources, sometimes making it their home. In addition to the native Chumash, European explorers, Aleut sea otter hunters, Chinese abalone fishermen, Spanish missionaries, Mexican and American ranchers, and the US military all have left their mark on the Santa Rosa landscape. Visitors can see relics of these occupations in remnants of fishing camps, water troughs and fence lines, the pier where cattle were loaded and unloaded, buildings and equipment of the historic Vail and Vickers ranch at Bechers Bay, and remains of the military installations.", location_id:10, cost:15, link:"https://www.recreation.gov/camping/campgrounds/232497"},
    {name: "Santa Cruz Scorpion", description:"Fantastic ocean views and relaxing beach time is practically guaranteed at Scorpion Canyon Campground, the most family-friendly campsite on Santa Cruz Island. Set on the eastern part of the island, the campground is a short hike from the pier and is sheltered from harsh ocean winds. The largest of California's Channel Islands, Santa Cruz Island is one of the five islands that make up the Channel Islands National Park. The island is rich in cultural history, magnificent landscapes, and unique flora and fauna. Native American Indians inhabited the island for over 10,000 years and Europeans explored and ranched on the island for over 150 years. Over 600 plant species, 140 land birds, 11 land mammals and a handful of amphibians and reptiles call the island their home. The island fox and island scrub-jay are exciting finds, as they're unique to the island, found nowhere else in the world. For more information about Santa Cruz Island visit: https://www.nps.gov/chis/planyourvisit/santa-cruz-island.htm .", location_id:10, cost:15, link:"https://www.recreation.gov/camping/campgrounds/232498"},
    {name: "Anacapa Island", description:"Anacapa Island, the closest Channel Island to the mainland of California, is comprised of three islets (appropriately named East, Middle, and West Anacapa Islands). Waves have eroded the volcanic island, creating towering sea cliffs, sea caves, and natural bridges, such as forty-foot-high Arch Rock -- a symbol of Anacapa and Channel Islands National Park.", location_id:10, cost: 15, link:"https://www.recreation.gov/camping/campgrounds/232502"},
    {name: "Cottonwood Campground", description:"Cottonwood Campground is one of the best places in Joshua Tree National Park for stargazing and wildflower viewing. Easy access from Interstate 10, makes it a popular stopover for travelers. Visitors who enjoy warm, dry winters flock to Joshua Tree from October through May, when temperatures reach between 70 to 90-degrees during the day and drop to 40 to 60-degrees at night. Summer is the park's off-season due to the uncomfortably high desert heat. Cottonwood Campground is at an elevation of 3,000 ft. and has little shade from vegetation.", location_id:11, cost: 25, link:"https://www.recreation.gov/camping/campgrounds/272299"},
    {name: "Jumbo Rocks Campground", description:"Jumbo Rocks Campground lies amid the huge, steep rock formations for which Joshua Tree National Park is known. Close proximity to many boulders and rock formations, it is a popular camping location for families with kids. Jumbo Rocks is one of four campgrounds in the park that can be reserved during the busy winter season; it is open on a first-come, first-served basis from June 9 through August 30. Travelers who enjoy warm, dry winters flock to Joshua Tree from October through May, when temperatures hover between 70-90 degrees during the day and drop to a 40-60 degree range at night. Summer is the park's off-season due to the uncomfortably-high desert heat. Jumbo Rocks is at an elevation of 4,380 feet.", location_id:11, cost:20, link:"https://www.recreation.gov/camping/campgrounds/272300"},
    {name: "Indian Cove Campground", description: "Indian Cove Campground lies amid the huge, steep rock formations for which Joshua Tree National Park is known. Because of its proximity to many rock climbing routes, it is a popular camping location for climbers. Indian Cove is one of four campgrounds in the park that can be reserved during the busy winter season; it is open on a first-come, first-served basis from May 25 to September 3.", location_id:11, cost:25, link:"https://www.recreation.gov/camping/campgrounds/232472"},
    {name: "Black Rock Campground", description:"Black Rock Campground lies among one of the thickest Joshua tree forests in Joshua Tree National Park. Its location on the park's northern perimeter makes it a popular rest stop for hikers, birders, horseback riders and RV campers. Black Rock is one of four campgrounds in the national park that can be reserved during the busy winter season; it is open on a first-come, first-served basis from May 25 through September 3.", location_id:11, cost:25, link:"https://www.recreation.gov/camping/campgrounds/232473"},
    {name: "Furnace Creek", description:"If you choose to camp in this beautiful land of extremes, there are 9 National Park Service campgrounds to choose from (though some are seasonally closed). Furnace Creek Campground is the only campground in the park that is reservable - all others are first-come, first-serve. Furnace Creek is also the only NPS campground that has hookup sites and designated group sites. It is highly recommended that you make a reservation if you want to stay in Furnace Creek during the reservation window (October 15 - April 15) - there are rarely sites available until the first-come, first-serve season.", location_id:12, cost:16, link:"https://www.recreation.gov/camping/campgrounds/232496"},
    {name: ""}
]


locations = [
    {name: "Angeles National Forest"},
    {name: "Sequoia and Kings Canyon National Park"},
    {name: "Los Padres National Forest"},
    {name: "Inyo National Forest"},
    {name: "Yosemite National Park"},
    {name: "Santa Monica Mountains"},
    {name: "Malibu State Park"},
    {name: "Mount San Jacinto State Park"},
    {name: "San Bernardino Mountains"},
    {name: "Channel Islands National Park"},
    {name: "Joshua Tree National Park"},
    {name: "Death Valley National Park"}
]

locations.each do |location|
        Location.create(location)
end

campgrounds.each do |campground| 
    Campground.create(campground)
end